//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zero_hungerEntities1 : DbContext
    {
        public zero_hungerEntities1()
            : base("name=zero_hungerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notificationn> Notificationns { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RequestForEmployee> RequestForEmployees { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<SignUp> SignUps { get; set; }
    }
}
